#!/bin/bash

cd /usr/lib/vmware/modules/source
tar xf vmmon.tar
tar xf vmnet.tar

cd /usr/lib/vmware/modules/source/vmmon-only
make

cd /usr/lib/vmware/modules/source/vmnet-only
make

cd ..
mkdir -p /lib/modules/`uname -r`/misc
cp vmmon.o /lib/modules/`uname -r`/misc/vmmon.ko
cp vmmon.o /lib/modules/`uname -r`/kernel/drivers/misc/vmmon.ko
cp vmmon.o /lib/modules/*/kernel/drivers/misc/vmmon.ko
cp vmmon.o /lib/modules/*/misc/vmmon.ko
cp vmnet.o /lib/modules/`uname -r`/misc/vmnet.ko
cp vmnet.o /lib/modules/`uname -r`/kernel/drivers/misc/vmnet.ko
cp vmnet.o /lib/modules/*/misc/vmnet.ko
cp vmnet.o /lib/modules/*/kernel/drivers/misc/vmnet.ko

depmod -a
/etc/init.d/vmware restart
